name: fate

on:
  workflow_dispatch:

jobs:
  win32:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, windows-11-arm]
        arch: [amd64, arm64]
        compiler: [clang-msvc, clang-cl-msvc, msvc, icx-win]
        asan: [false, true]
        shared: [false, true]
        debug: [false, true]
        assert: [false, true]
        cet: [false, true]
        exclude:
          - arch: amd64
            os: windows-11-arm
          - arch: arm64
            os: windows-2025
          # Enable once aarch64-pc-windows-msvc/clang_rt.asan.lib is available on the runner
          - arch: arm64
            asan: true
          - shared: true
            asan: true
          - debug: true
            shared: true
          - debug: true
            asan: true
          - debug: true
            compiler: clang-msvc
          - debug: true
            compiler: clang-cl-msvc
          - assert: true
            compiler: clang-cl-msvc
          - assert: true
            compiler: clang-msvc
          - assert: true
            asan: true
          - assert: true
            shared: true
          - assert: true
            debug: true
          - compiler: icx-win
            asan: true
          - compiler: icx-win
            shared: true
          - compiler: icx-win
            debug: true
          - compiler: icx-win
            assert: true
          - compiler: icx-win
            arch: arm64
          - cet: true
            compiler: clang-msvc
          - cet: true
            compiler: clang-cl-msvc
          - cet: true
            asan: true
          - cet: true
            shared: true
          - cet: true
            debug: true
          - cet: true
            assert: true
          # Doesn't work currently
          - compiler: icx-win
    env:
      CONF: ${{ matrix.arch }}-${{ matrix.compiler }}${{ matrix.asan && '-asan' || '' }}${{ matrix.shared && '-shared' || '' }}${{ matrix.debug && '-debug' || '' }}${{ matrix.assert && '-assert' || '' }}${{ matrix.cet && '-cet' || '' }}
      VS: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise"
      VULKAN_ROOT: "C:\\VulkanSDK"
      MSYSTEM: MSYS
      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
    steps:
      - name: Print CPU Info
        shell: pwsh
        working-directory: ${{ runner.temp }}
        run: |
          curl -OL https://download.sysinternals.com/files/Coreinfo.zip
          Expand-Archive -Path Coreinfo.zip -DestinationPath coreinfo
          $exe = if ("${{ matrix.arch }}" -eq "arm64") { "Coreinfo64a.exe" } else { "Coreinfo64.exe" }
          & .\coreinfo\$exe -accepteula
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: inherit
          update: true
          install: >-
            gzip
            make
            nasm
            openssh
            rsync
            tar
      - name: Install Intel oneAPI DPC++/C++ Compiler
        if: ${{ matrix.compiler == 'icx-win' }}
        shell: pwsh
        working-directory: ${{ runner.temp }}
        run: |
          curl -OL https://registrationcenter-download.intel.com/akdlm/IRC_NAS/47a201d7-d4cd-4079-a2d8-0e66b860aaaa/intel-dpcpp-cpp-compiler-2025.2.0.536_offline.exe
          & .\intel-dpcpp-cpp-compiler-2025.2.0.536_offline.exe --silent --eula accept
      - name: Install Vulkan SDK
        if: ${{ !matrix.cet }}
        shell: pwsh
        working-directory: ${{ runner.temp }}
        run: |
          $arch = if ("${{ matrix.arch }}" -eq "arm64") { "warm" } else { "windows" }
          curl https://sdk.lunarg.com/sdk/download/latest/$arch/vulkan_sdk.exe -o vulkan-sdk.exe
          & .\vulkan-sdk.exe in --al -c -t $env:VULKAN_ROOT com.lunarg.vulkan com.lunarg.vulkan.core com.lunarg.vulkan.debug com.lunarg.vulkan.sdl2
      - name: Disable autocrlf
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For fate version string
          repository: ffmpeg/ffmpeg
          path: .github/fate/src
      - name: Checkout gas-preprocessor
        if: ${{ matrix.compiler == 'msvc' || matrix.compiler == 'clang-cl-msvc' }}
        uses: actions/checkout@v4
        with:
          repository: ffmpeg/gas-preprocessor
          path: gas-preprocessor
      - name: Checkout zlib
        uses: actions/checkout@v4
        with:
          repository: madler/zlib
          # Switch to stable release when this is available https://github.com/madler/zlib/issues/787
          ref: develop
          path: zlib
      - name: Build zlib
        shell: pwsh
        working-directory: zlib
        run: |
          # Workaround for https://github.com/madler/zlib/issues/787#issuecomment-3094568653
          (Get-Content "zconf.h") -replace '#if HAVE_UNISTD_H-0', '#if defined(HAVE_UNISTD_H) && HAVE_UNISTD_H' | Set-Content "zconf.h"
          Import-Module "$env:VS\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath $env:VS -SkipAutomaticLocation -DevCmdArguments "-arch=${{ matrix.arch }} -host_arch=${{ matrix.arch }}"
          $crt = if (${{ matrix.debug }}) { "MultiThreadedDebugDLL" } else { "MultiThreadedDLL" }
          $cflags = ""
          $ldflags = ""
          if ("${{ matrix.cet }}" -eq "true") {
            if ("${{ matrix.arch }}" -eq "amd64") {
              $cflags  = "-guard:ehcont"
              $ldflags = "-guard:ehcont -CETCOMPAT"
            } elseif ("${{ matrix.arch }}" -eq "arm64") {
              $cflags  = "-guard:ehcont -guard:signret"
              $ldflags = "-guard:ehcont -guard:delayloadsignret"
            }
          }
          cmake -GNinja -Bbuild `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}\install `
            -DCMAKE_MSVC_RUNTIME_LIBRARY="$crt" `
            -DCMAKE_C_FLAGS="$cflags" `
            -DCMAKE_EXE_LINKER_FLAGS="$ldflags" `
            -DCMAKE_SHARED_LINKER_FLAGS="$ldflags"
          ninja -C build install
          # FFmpeg replaces -lz with zlib.lib for MSVC targets
          cp -force ${{ runner.temp }}\install\lib\zs.lib ${{ runner.temp }}\install\lib\zlib.lib
          cp -force ${{ runner.temp }}\install\lib\zs.lib ${{ runner.temp }}\install\lib\z.lib
      - name: Restore Cached FATE Samples
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-dummy
          restore-keys: fate-samples-
      - name: Sync FATE Samples
        id: samples
        shell: msys2 {0}
        run: |
          mkdir -p .github/fate/samples
          rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ .github/fate/samples/
          echo "hash=$(find .github/fate/samples -type f | tr '\\' '/' | LC_ALL=C sort | tr -d '\r' | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache FATE Samples
        if: ${{ format('fate-samples-{0}', steps.samples.outputs.hash) != steps.cache.outputs.cache-matched-key }}
        uses: actions/cache/save@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-${{ steps.samples.outputs.hash }}
      - name: Set up SSH
        shell: msys2 {0}
        env:
          HOST: fate.ffmpeg.org
          FINGERPRINT: "76:9f:68:32:04:1e:d5:d4:ec:47:3f:dc:fc:18:17:86"
        run: |
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          ssh-keyscan -t ecdsa "$HOST" > "$HOME/.ssh/known_hosts"
          SERVER_FINGERPRINT="$(ssh-keygen -E md5 -lf "$HOME/.ssh/known_hosts" | grep "$HOST" | awk '{gsub(/^MD5:/, "", $2); print $2}')"
          if [ "$SERVER_FINGERPRINT" != "$FINGERPRINT" ]; then
            echo "Fingerprint $SERVER_FINGERPRINT does not match expected $FINGERPRINT"
            exit 1
          fi
          echo "${{ secrets.FATE_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
      - name: Build
        id: build
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $PSNativeCommandUseErrorActionPreference = $true

          # GHA images have polluted PATH, clean it up a bit
          $env:PATH = ($env:PATH -split ';' | Where-Object { $_ -ne 'C:\Program Files\LLVM\bin' -and `
                                                             $_ -ne 'C:\Program Files\CMake\bin' -and `
                                                             $_ -ne 'C:\Strawberry\c\bin' }) -join ';'
          $env:PATH += ";$PWD\gas-preprocessor"
          $env:LIB += ";$env:VULKAN_ROOT\Lib"
          $env:INCLUDE += ";$env:VULKAN_ROOT\Include"

          if ("${{ matrix.compiler }}" -eq "icx-win") {
              $env:PATH += ";C:\Program Files (x86)\Intel\oneAPI\compiler\latest\bin"
          }

          Import-Module "$env:VS\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath $env:VS -SkipAutomaticLocation -DevCmdArguments "-arch=${{ matrix.arch }} -host_arch=${{ matrix.arch }}"

          cd .github/fate/src
          msys2 -ec 'PKG_CONFIG_PATH=`cygpath -a ''${{ runner.temp }}\install\lib\pkgconfig''` PATH="$PATH:$PWD/../install/bin" ./tests/fate.sh ../${{ env.CONF }}'
      - name: Print version
        if: always()
        run: |
          cat .github/fate/version-${{ env.CONF }}
      - name: Print report
        if: always()
        run: |
          cat .github/fate/report
      - name: Print configure.log
        if: always()
        run: |
          cat .github/fate/configure.log
      - name: Print compile.log
        if: always()
        run: |
          cat .github/fate/compile.log
      - name: Print test.log
        if: always()
        run: |
          cat .github/fate/test.log

  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        arch: [amd64, arm64]
        compiler: [clang, icx]
        asan: [false, true]
        asm: [false, true]
        msan: [false, true]
        shared: [false]
        cet: [false, true]
        sde: [false, true]
        include:
          - compiler: clang
            compiler_pkg: clang
          - compiler: icx
            compiler_pkg: intel-oneapi-compiler-dpcpp-cpp
        exclude:
          - arch: amd64
            os: ubuntu-24.04-arm
          - arch: arm64
            os: ubuntu-24.04
          - compiler: clang
            asan: false
            msan: false
            cet: false
            sde: false
          - msan: true
            asan: true
          - msan: true
            arch: arm64
          - msan: true
            asm: true
          - compiler: icx
            asan: true
          - compiler: icx
            msan: true
          - compiler: icx
            asm: true
          - compiler: icx
            arch: arm64
          - cet: true
            compiler: icx
          - cet: true
            asan: true
          - cet: true
            msan: true
          - cet: true
            asm: false
          - sde: true
            arch: arm64
          - sde: true
            compiler: icx
          - sde: true
            asan: true
          - sde: true
            msan: true
          - sde: true
            cet: true
          - sde: true
            asm: false
    env:
      CONF: ${{ matrix.arch }}-${{ matrix.compiler }}${{ matrix.asan && '-asan' || '' }}${{ matrix.msan && '-msan' || '' }}${{ matrix.shared && '-shared' || '' }}${{ matrix.cet && '-cet' || '' }}${{ matrix.sde && '-sde' || '' }}${{ matrix.asm && '-asm' || '' }}
      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
      GLIBC_TUNABLES: glibc.cpu.hwcaps=SHSTK
    steps:
      - name: Print CPU Info
        run: |
          cat /proc/cpuinfo
      - name: Add Nightly LLVM
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: |
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          echo "deb https://apt.llvm.org/noble/ llvm-toolchain-noble main" | sudo tee /etc/apt/sources.list.d/llvm.list
      - name: Add Intel oneAPI DPC++/C++ Compiler
        if: ${{ matrix.compiler == 'icx' }}
        run: |
          curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo tee /etc/apt/trusted.gpg.d/apt.intel.asc
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/intel.list
      - name: Create Vulkan SDK directory
        if: ${{ !matrix.cet && !matrix.sde }}
        run: |
          sudo mkdir -p /opt/vulkan-sdk
          sudo chown $USER:$USER /opt/vulkan-sdk
      - name: Install Vulkan SDK
        if: ${{ !matrix.cet && !matrix.sde }}
        working-directory: /opt/vulkan-sdk
        run: |
          curl -O https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.xz
          tar xvf vulkan-sdk.tar.xz
      - name: Build Vulkan SDK
        if: ${{ matrix.os == 'ubuntu-24.04-arm' && !matrix.cet }}
        working-directory: /opt/vulkan-sdk
        run: |
          cd 1.*
          ./vulkansdk --maxjobs vulkan-loader vulkan-headers shaderc
      - name: Download Intel SDE
        if: ${{ matrix.sde }}
        working-directory: ${{ runner.temp }}
        run: |
          curl -O https://downloadmirror.intel.com/859732/sde-external-9.58.0-2025-06-16-lin.tar.xz
          tar xvf sde-external-9.58.0-2025-06-16-lin.tar.xz
          echo "SDE_PATH=${{ runner.temp }}/sde-external-9.58.0-2025-06-16-lin" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.compiler_pkg }} git libsdl2-dev libxml2-utils lld llvm make nasm openssh-client pkgconf rsync zlib1g-dev
      - uses: actions/checkout@v4
      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For fate version string
          repository: ffmpeg/ffmpeg
          path: .github/fate/src
      - name: Checkout zlib
        if: matrix.msan
        uses: actions/checkout@v4
        with:
          repository: madler/zlib
          ref: develop
          path: zlib
      - name: Build zlib
        if: matrix.msan
        working-directory: zlib
        run: |
          cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
                -DCMAKE_C_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer" \
                -DZLIB_BUILD_TESTING=OFF -DZLIB_BUILD_SHARED=OFF
          sudo ninja -C build install
      - name: Restore Cached FATE Samples
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-dummy
          restore-keys: fate-samples-
      - name: Sync FATE Samples
        id: samples
        run: |
          mkdir -p .github/fate/samples
          rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ .github/fate/samples/
          echo "hash=$(find .github/fate/samples -type f | tr '\\' '/' | LC_ALL=C sort | tr -d '\r' | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache FATE Samples
        if: ${{ format('fate-samples-{0}', steps.samples.outputs.hash) != steps.cache.outputs.cache-matched-key }}
        uses: actions/cache/save@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-${{ steps.samples.outputs.hash }}
      - name: Set up SSH
        env:
          HOST: fate.ffmpeg.org
          FINGERPRINT: "76:9f:68:32:04:1e:d5:d4:ec:47:3f:dc:fc:18:17:86"
        run: |
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          ssh-keyscan -t ecdsa "$HOST" > "$HOME/.ssh/known_hosts"
          SERVER_FINGERPRINT="$(ssh-keygen -E md5 -lf "$HOME/.ssh/known_hosts" | grep "$HOST" | awk '{gsub(/^MD5:/, "", $2); print $2}')"
          if [ "$SERVER_FINGERPRINT" != "$FINGERPRINT" ]; then
            echo "Fingerprint $SERVER_FINGERPRINT does not match expected $FINGERPRINT"
            exit 1
          fi
          echo "${{ secrets.FATE_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
      - name: Build
        id: build
        run: |
          if [ "${{ matrix.compiler }}" = "icx" ]; then
            source /opt/intel/oneapi/setvars.sh
          fi
          if [ "${{ matrix.cet }}" = "false" ] && [ "${{ matrix.sde }}" != "true" ]; then
            source /opt/vulkan-sdk/1.*/setup-env.sh
          fi
          if [ "${{ matrix.sde }}" = "true" ]; then
            export PATH="$SDE_PATH:$PATH"
            echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
          fi
          cd .github/fate/src
          ./tests/fate.sh ../${{ env.CONF }}
      - name: Print version
        if: always()
        run: |
          cat .github/fate/version-${{ env.CONF }}
      - name: Print report
        if: always()
        run: |
          cat .github/fate/report
      - name: Print configure.log
        if: always()
        run: |
          cat .github/fate/configure.log
      - name: Print config.log
        if: always()
        run: |
          cat .github/fate/build/ffbuild/config.log
      - name: Print compile.log
        if: always()
        run: |
          cat .github/fate/compile.log
      - name: Print test.log
        if: always()
        run: |
          cat .github/fate/test.log
      - name: readelf
        run: |
          find .github/fate/install/
          readelf -n .github/fate/install/bin/ffmpeg

  debian:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        arch: [amd64, arm64]
        compiler: [gcc-snapshot]
        exclude:
          - arch: amd64
            os: ubuntu-24.04-arm
          - arch: arm64
            os: ubuntu-24.04
    container:
      image: debian:unstable-slim
    env:
      CONF: ${{ matrix.arch }}-${{ matrix.compiler }}
      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
    steps:
      - name: Print CPU Info
        run: |
          cat /proc/cpuinfo
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y ${{ matrix.compiler }} git libsdl2-dev libvulkan-dev glslang-dev spirv-tools libxml2-utils make mold nasm openssh-client pkgconf rsync zlib1g-dev
      - uses: actions/checkout@v4
      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For fate version string
          repository: ffmpeg/ffmpeg
          path: .github/fate/src
      - name: Restore Cached FATE Samples
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-dummy
          restore-keys: fate-samples-
      - name: Sync FATE Samples
        id: samples
        run: |
          mkdir -p .github/fate/samples
          rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ .github/fate/samples/
          echo "hash=$(find .github/fate/samples -type f | tr '\\' '/' | LC_ALL=C sort | tr -d '\r' | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache FATE Samples
        if: ${{ format('fate-samples-{0}', steps.samples.outputs.hash) != steps.cache.outputs.cache-matched-key }}
        uses: actions/cache/save@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-${{ steps.samples.outputs.hash }}
      - name: Set up SSH
        env:
          HOST: fate.ffmpeg.org
          FINGERPRINT: "76:9f:68:32:04:1e:d5:d4:ec:47:3f:dc:fc:18:17:86"
        run: |
          export HOME="/root"
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          ssh-keyscan -t ecdsa "$HOST" > "$HOME/.ssh/known_hosts"
          chmod 644 "$HOME/.ssh/known_hosts"
          SERVER_FINGERPRINT="$(ssh-keygen -E md5 -lf "$HOME/.ssh/known_hosts" | grep "$HOST" | awk '{gsub(/^MD5:/, "", $2); print $2}')"
          if [ "$SERVER_FINGERPRINT" != "$FINGERPRINT" ]; then
            echo "Fingerprint $SERVER_FINGERPRINT does not match expected $FINGERPRINT"
            exit 1
          fi
          echo "${{ secrets.FATE_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
      - name: Build
        id: build
        run: |
          export PATH="/usr/lib/gcc-snapshot/bin:${PATH}"
          export LD_RUN_PATH="/usr/lib/gcc-snapshot/lib"
          gcc --version
          cd .github/fate/src
          ./tests/fate.sh ../${{ env.CONF }}
      - name: Print version
        if: always()
        run: |
          cat .github/fate/version-${{ env.CONF }}
      - name: Print report
        if: always()
        run: |
          cat .github/fate/report
      - name: Print configure.log
        if: always()
        run: |
          cat .github/fate/configure.log
      - name: Print compile.log
        if: always()
        run: |
          cat .github/fate/compile.log
      - name: Print test.log
        if: always()
        run: |
          cat .github/fate/test.log
