name: fate

on:
  workflow_dispatch:

jobs:
  win32:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, windows-11-arm]
        arch: [amd64, arm64]
        compiler: [clang-msvc, clang-cl-msvc, msvc]
        asan: [false, true]
        shared: [false, true]
        debug: [false, true]
        assert: [false, true]
        exclude:
          - arch: amd64
            os: windows-11-arm
          - arch: arm64
            os: windows-2025
          # Enable once aarch64-pc-windows-msvc/clang_rt.asan.lib is available on the runner
          - arch: arm64
            asan: true
          - shared: true
            asan: true
          - debug: true
            shared: true
          - debug: true
            asan: true
          - debug: true
            compiler: clang-msvc
          - debug: true
            compiler: clang-cl-msvc
          - compiler: clang-msvc
          - assert: true
            compiler: clang-cl-msvc
          - assert: true
            compiler: clang-msvc
          - assert: true
            asan: true
          - assert: true
            shared: true
          - assert: true
            debug: true
    env:
      CONF: ${{ matrix.arch }}-${{ matrix.compiler }}${{ matrix.asan && '-asan' || '' }}${{ matrix.shared && '-shared' || '' }}${{ matrix.debug && '-debug' || '' }}${{ matrix.assert && '-assert' || '' }}
      VS: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise"
      MSYSTEM: MSYS
      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: inherit
          update: true
          install: >-
            gzip
            make
            nasm
            openssh
            rsync
            tar
      - name: Disable autocrlf
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For fate version string
          repository: ffmpeg/ffmpeg
          path: .github/fate/src
      - name: Checkout gas-preprocessor
        if: ${{ matrix.compiler == 'msvc' || matrix.compiler == 'clang-cl-msvc' }}
        uses: actions/checkout@v4
        with:
          repository: ffmpeg/gas-preprocessor
          path: gas-preprocessor
      - name: Checkout zlib
        uses: actions/checkout@v4
        with:
          repository: madler/zlib
          # Switch to stable release when this is available https://github.com/madler/zlib/issues/787
          ref: develop
          path: zlib
      - name: Build zlib
        shell: pwsh
        working-directory: zlib
        run: |
          # Workaround for https://github.com/madler/zlib/issues/787#issuecomment-3094568653
          (Get-Content "zconf.h") -replace '#if HAVE_UNISTD_H-0', '#if defined(HAVE_UNISTD_H) && HAVE_UNISTD_H' | Set-Content "zconf.h"
          Import-Module "$env:VS\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath $env:VS -SkipAutomaticLocation -DevCmdArguments "-arch=${{ matrix.arch }} -host_arch=${{ matrix.arch }}"
          $crt = if (${{ matrix.debug }}) { "MultiThreadedDebug" } else { "MultiThreaded" }
          cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}\install -DCMAKE_MSVC_RUNTIME_LIBRARY="$crt"
          ninja -C build install
          # FFmpeg replaces -lz with zlib.lib for MSVC targets
          cp -force ${{ runner.temp }}\install\lib\zs.lib ${{ runner.temp }}\install\lib\zlib.lib
          cp -force ${{ runner.temp }}\install\lib\zs.lib ${{ runner.temp }}\install\lib\z.lib
      - name: Restore Cached FATE Samples
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-dummy
          restore-keys: fate-samples-
      - name: Sync FATE Samples
        id: samples
        shell: msys2 {0}
        run: |
          mkdir -p .github/fate/samples
          rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ .github/fate/samples/
          echo "hash=$(find .github/fate/samples -type f | tr '\\' '/' | LC_ALL=C sort | tr -d '\r' | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache FATE Samples
        if: ${{ format('fate-samples-{0}', steps.samples.outputs.hash) != steps.cache.outputs.cache-matched-key }}
        uses: actions/cache/save@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-${{ steps.samples.outputs.hash }}
      - name: Set up SSH
        shell: msys2 {0}
        env:
          HOST: fate.ffmpeg.org
          FINGERPRINT: "76:9f:68:32:04:1e:d5:d4:ec:47:3f:dc:fc:18:17:86"
        run: |
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          ssh-keyscan -t ecdsa "$HOST" > "$HOME/.ssh/known_hosts"
          SERVER_FINGERPRINT="$(ssh-keygen -E md5 -lf "$HOME/.ssh/known_hosts" | grep "$HOST" | awk '{gsub(/^MD5:/, "", $2); print $2}')"
          if [ "$SERVER_FINGERPRINT" != "$FINGERPRINT" ]; then
            echo "Fingerprint $SERVER_FINGERPRINT does not match expected $FINGERPRINT"
            exit 1
          fi
          echo "${{ secrets.FATE_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
      - name: Build
        id: build
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $PSNativeCommandUseErrorActionPreference = $true

          # GHA images have polluted PATH, clean it up a bit
          $env:PATH = ($env:PATH -split ';' | Where-Object { $_ -ne 'C:\Program Files\CMake\bin' -and `
                                                             $_ -ne 'C:\Strawberry\c\bin' }) -join ';'
          $env:PATH += ";$PWD\gas-preprocessor"

          Import-Module "$env:VS\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath $env:VS -SkipAutomaticLocation -DevCmdArguments "-arch=${{ matrix.arch }} -host_arch=${{ matrix.arch }}"

          $env:PATH = 'C:\Program Files\LLVM\bin;' + $env:PATH

          cd .github/fate/src
          msys2 -ec 'PKG_CONFIG_PATH=`cygpath -a ''${{ runner.temp }}\install\lib\pkgconfig''` ./tests/fate.sh ../${{ env.CONF }}'
      - name: Print version
        if: always()
        run: |
          cat .github/fate/version-${{ env.CONF }}
      - name: Print report
        if: always()
        run: |
          cat .github/fate/report
      - name: Print configure.log
        if: always()
        run: |
          cat .github/fate/configure.log
      - name: Print compile.log
        if: always()
        run: |
          cat .github/fate/compile.log
      - name: Print test.log
        if: always()
        run: |
          cat .github/fate/test.log

  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        arch: [amd64, arm64]
        compiler: [clang]
        asan: [false, true]
        asm: [false, true]
        msan: [false, true]
        shared: [false]
        exclude:
          - arch: amd64
            os: ubuntu-24.04-arm
          - arch: arm64
            os: ubuntu-24.04
          - asan: false
            msan: false
          - msan: true
            asan: true
          - msan: true
            arch: arm64
          - msan: true
            asm: true
    env:
      CONF: ${{ matrix.arch }}-${{ matrix.compiler }}${{ matrix.asan && '-asan' || '' }}${{ matrix.msan && '-msan' || '' }}${{ matrix.shared && '-shared' || '' }}${{ matrix.asm && '-asm' || '' }}
      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
    steps:
      - name: Add Nightly LLVM
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: |
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          echo "deb https://apt.llvm.org/noble/ llvm-toolchain-noble main" | sudo tee /etc/apt/sources.list.d/llvm.list
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.compiler }} git libxml2-utils lld llvm make nasm openssh-client pkgconf rsync zlib1g-dev
      - uses: actions/checkout@v4
      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For fate version string
          repository: ffmpeg/ffmpeg
          path: .github/fate/src
      - name: Checkout zlib
        if: matrix.msan
        uses: actions/checkout@v4
        with:
          repository: madler/zlib
          ref: develop
          path: zlib
      - name: Build zlib
        if: matrix.msan
        working-directory: zlib
        run: |
          cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
                -DCMAKE_C_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer" \
                -DZLIB_BUILD_TESTING=OFF -DZLIB_BUILD_SHARED=OFF
          sudo ninja -C build install
      - name: Restore Cached FATE Samples
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-dummy
          restore-keys: fate-samples-
      - name: Sync FATE Samples
        id: samples
        run: |
          mkdir -p .github/fate/samples
          rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ .github/fate/samples/
          echo "hash=$(find .github/fate/samples -type f | tr '\\' '/' | LC_ALL=C sort | tr -d '\r' | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache FATE Samples
        if: ${{ format('fate-samples-{0}', steps.samples.outputs.hash) != steps.cache.outputs.cache-matched-key }}
        uses: actions/cache/save@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-${{ steps.samples.outputs.hash }}
      - name: Set up SSH
        env:
          HOST: fate.ffmpeg.org
          FINGERPRINT: "76:9f:68:32:04:1e:d5:d4:ec:47:3f:dc:fc:18:17:86"
        run: |
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          ssh-keyscan -t ecdsa "$HOST" > "$HOME/.ssh/known_hosts"
          SERVER_FINGERPRINT="$(ssh-keygen -E md5 -lf "$HOME/.ssh/known_hosts" | grep "$HOST" | awk '{gsub(/^MD5:/, "", $2); print $2}')"
          if [ "$SERVER_FINGERPRINT" != "$FINGERPRINT" ]; then
            echo "Fingerprint $SERVER_FINGERPRINT does not match expected $FINGERPRINT"
            exit 1
          fi
          echo "${{ secrets.FATE_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
      - name: Build
        id: build
        run: |
          cd .github/fate/src
          ./tests/fate.sh ../${{ env.CONF }}
      - name: Print version
        if: always()
        run: |
          cat .github/fate/version-${{ env.CONF }}
      - name: Print report
        if: always()
        run: |
          cat .github/fate/report
      - name: Print configure.log
        if: always()
        run: |
          cat .github/fate/configure.log
      - name: Print compile.log
        if: always()
        run: |
          cat .github/fate/compile.log
      - name: Print test.log
        if: always()
        run: |
          cat .github/fate/test.log

  debian:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        arch: [amd64, arm64]
        compiler: [gcc-snapshot]
        exclude:
          - arch: amd64
            os: ubuntu-24.04-arm
          - arch: arm64
            os: ubuntu-24.04
    container:
      image: debian:unstable-slim
    env:
      CONF: ${{ matrix.arch }}-${{ matrix.compiler }}
      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y ${{ matrix.compiler }} git libxml2-utils make mold nasm openssh-client pkgconf rsync zlib1g-dev
      - uses: actions/checkout@v4
      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For fate version string
          repository: ffmpeg/ffmpeg
          path: .github/fate/src
      - name: Restore Cached FATE Samples
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-dummy
          restore-keys: fate-samples-
      - name: Sync FATE Samples
        id: samples
        run: |
          mkdir -p .github/fate/samples
          rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ .github/fate/samples/
          echo "hash=$(find .github/fate/samples -type f | tr '\\' '/' | LC_ALL=C sort | tr -d '\r' | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache FATE Samples
        if: ${{ format('fate-samples-{0}', steps.samples.outputs.hash) != steps.cache.outputs.cache-matched-key }}
        uses: actions/cache/save@v4
        with:
          path: .github/fate/samples
          enableCrossOsArchive: true
          key: fate-samples-${{ steps.samples.outputs.hash }}
      - name: Set up SSH
        env:
          HOST: fate.ffmpeg.org
          FINGERPRINT: "76:9f:68:32:04:1e:d5:d4:ec:47:3f:dc:fc:18:17:86"
        run: |
          export HOME="/root"
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          ssh-keyscan -t ecdsa "$HOST" > "$HOME/.ssh/known_hosts"
          chmod 644 "$HOME/.ssh/known_hosts"
          SERVER_FINGERPRINT="$(ssh-keygen -E md5 -lf "$HOME/.ssh/known_hosts" | grep "$HOST" | awk '{gsub(/^MD5:/, "", $2); print $2}')"
          if [ "$SERVER_FINGERPRINT" != "$FINGERPRINT" ]; then
            echo "Fingerprint $SERVER_FINGERPRINT does not match expected $FINGERPRINT"
            exit 1
          fi
          echo "${{ secrets.FATE_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
      - name: Build
        id: build
        run: |
          export PATH="/usr/lib/gcc-snapshot/bin:${PATH}"
          export LD_RUN_PATH="/usr/lib/gcc-snapshot/lib"
          gcc --version
          cd .github/fate/src
          ./tests/fate.sh ../${{ env.CONF }}
      - name: Print version
        if: always()
        run: |
          cat .github/fate/version-${{ env.CONF }}
      - name: Print report
        if: always()
        run: |
          cat .github/fate/report
      - name: Print configure.log
        if: always()
        run: |
          cat .github/fate/configure.log
      - name: Print compile.log
        if: always()
        run: |
          cat .github/fate/compile.log
      - name: Print test.log
        if: always()
        run: |
          cat .github/fate/test.log
